config/routes.rb
Rails.application.routes.draw do
	
    resources :players
    root 'players#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ActiveRecord::Base
	require 'riotapi'

	before_save :downcase_players
	before_save :mod_champ_save

	# returns the player id
	def self.return_id(name)
		api = RiotApi.new
		info = api.get_summoner_id(name)
		info[name]["id"]
	end

	# return a list of champions a given summoner has played in ranked
	def self.return_summoner_champion_list(summoner_name)
		id = return_id(summoner_name)
		api = RiotApi.new
		full_stat = api.get_full_stats(id)
		full_stat["champions"]
	end

	# get the champion ID given the champion name
	def self.get_champion_id(champ_name)
		api = RiotApi.new
		champs = api.get_champion
		champs["data"][champ_name]["id"]
		
	end

	def self.determine_champion_probability(summoner_name, champ_name)

    champion_ids = return_summoner_champion_list(summoner_name).collect{|player| player["id"]}
    desired_champ_id = get_champion_id(champ_name)
    winrate = 0.0

    if champion_ids.include?(desired_champ_id)
      # get the desired champion array location
      hash = Hash[champion_ids.map.with_index.to_a]
      champ_array_location = hash[desired_champ_id]

      # calcul du winrate
      player_stat = return_summoner_champion_list(summoner_name)[champ_array_location]["stats"]
      total_played = player_stat["totalSessionsPlayed"]
      total_won = player_stat["totalSessionsWon"]
      winrate = (total_won.to_f / total_played.to_f)
      winrate.round(2) * 100
    else
      winrate = 0.5 * 100
    end
  end

	private

	#downcase des noms de joueurs
	def downcase_players
		self.p1.downcase!
		self.p2.downcase!
	end

	def mod_champ_save
    #split the word first. capitalize each individual word. Join them back with no spaces in between. 
    	self.c1 = c1.split.map(&:capitalize).join('')
    	self.c2 = c2.split.map(&:capitalize).join('')
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	def index
	end

	def create
	  @player = Player.new(players_params)
	  @player.save
	  redirect_to @player
	end

	def show
	  @player = Player.find(params[:id])
	end

	private

	def players_params
	  params.require(:player).permit(:p1, :p2, :c1, :c2)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

def wonned
  "<img src='http://40.media.tumblr.com/cbab7227ad515b94015eb82b1e2e1d47/tumblr_nea4i9gpfB1qgrdiqo2_1280.png' />".html_safe
end

def loosed
  "<img src='https://66.media.tumblr.com/fe76a4edc1d51b0a041ec8ee101e5fa0/tumblr_nea4i9gpfB1qgrdiqo1_1280.png' />".html_safe
end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>League Rivals</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Play" rel="stylesheet">
  	<link href="https://fonts.googleapis.com/css?family=Play:700" rel="stylesheet">
  	<%= stylesheet_link_tag "tether.min.css" %>
  	<%= stylesheet_link_tag "style.css" %>
  	<%= stylesheet_link_tag "bootstrap.min.css" %>
  	<%= stylesheet_link_tag "material.css" %>
  	<%= stylesheet_link_tag "mbr-additional.css" %>
  </head>

  <body>
    <%= yield %>
  </body>

 <%= javascript_include_tag "bootstrap.min.js" %>
<%= javascript_include_tag "jarallax.js" %>
<%= javascript_include_tag "jquery.min.js" %>
<%= javascript_include_tag "jquery.mb.YTPlayer.min.js" %>
<%= javascript_include_tag "script.js" %>

</html>

app/views/players/_footer.html.erb
<footer class="mbr-small-footer mbr-section mbr-section-nopadding" id="footer1-2" style="background-color: rgb(50, 50, 50); padding-top: 1.75rem; padding-bottom: 1.75rem;">
    
    <div class="container">
        <p class="text-xs-center">League Rivals isn't endorsed by Riot Games and doesn't reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.<br><br>League Rivals | <a href="https://github.com/Zepri/LeagueRivals" target="_blank" class="text-success">Github</a></p>
    </div>
</footer>

app/views/players/_form.html.erb
<!-- <!DOCTYPE html>
<html>
<head>
   Site made with Mobirise Website Builder v3.9.2, https://mobirise.com 
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v3.9.2, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="assets/images/logo.png" type="image/x-icon">
  <meta name="description" content="">
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;subset=latin">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
  <link rel="stylesheet" href="assets/bootstrap-material-design-font/css/material.css">
  <link rel="stylesheet" href="assets/tether/tether.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/theme/css/style.css">
  <link rel="stylesheet" href="assets/mobirise/css/mbr-additional.css" type="text/css">
  
  
  
</head>
<body>
<section class="mbr-section" id="pricing-table1-e" style="background-color: rgb(124, 112, 107); padding-top: 40px; padding-bottom: 120px;">

    

    <div class="mbr-section mbr-section__container mbr-section__container--middle">
      <div class="container">
          <div class="row">
              <div class="col-xs-12 text-xs-center">
                  
                  
              </div>
          </div>
      </div>
    </div>
  <%= form_for :player, url: players_path do |f| %>
    <div class="mbr-section mbr-section-nopadding mbr-price-table">
      <div class="row">
            <div class="col-xs-12 col-md-6 col-xl-4">
                <div class="mbr-plan card text-xs-center">
                    <div class="mbr-plan-header card-block">
                      
                      <div class="card-title">
                        <h3 class="mbr-plan-title"></h3>
                        <small class="mbr-plan-subtitle"></small>
                      </div>
                      <div class="card-text">
                          <div class="mbr-price">
                            <span class="mbr-price-value"></span>
                            <span class="mbr-price-figure"><%= f.label :p1, "Votre nom d'invocateur"  %>
                            <%= f.text_field :p1 %><br><br><%= f.label :c1, "Votre champion" %>
                            <%= f.text_field :c1 %><br></span><small class="mbr-price-term"></small>
                          </div>
                          <small class="mbr-plan-price-desc"></small>
                      </div>
                    </div>
                    <div class="mbr-plan-body card-block">
                      <div class="mbr-plan-list"></div>
                      <div class="mbr-plan-btn"><a href="https://mobirise.com" class="btn btn-white btn-white-outline">DEMO</a></div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-xl-4">
                <div class="mbr-plan card text-xs-center">
                    <div class="mbr-plan-header card-block">
                      
                      <div class="card-title">
                        <h3 class="mbr-plan-title"></h3>
                        <small class="mbr-plan-subtitle"></small>
                      </div>
                      <div class="card-text">
                          <div class="mbr-price">
                            <span class="mbr-price-value"></span>
                            <span class="mbr-price-figure"></span><small class="mbr-price-term"></small>
                          </div>
                          <small class="mbr-plan-price-desc"></small>
                      </div>
                    </div>
                    <div class="mbr-plan-body card-block">
                      <div class="mbr-plan-list"></div>
                      <div class="mbr-plan-btn"><a href="https://mobirise.com" class="btn btn-white btn-white-outline"><%= f.submit "Combattre" %></a></div>
                    </div>
                </div>
            </div>
            
            <div class="col-xs-12 col-md-6 col-xl-4">
                <div class="mbr-plan card text-xs-center">
                    <div class="mbr-plan-header card-block">
                      
                      <div class="card-title">
                        <h3 class="mbr-plan-title"></h3>
                        <small class="mbr-plan-subtitle"></small>
                      </div>
                      <div class="card-text">
                          <div class="mbr-price">
                            <span class="mbr-price-value"></span>
                            <span class="mbr-price-figure"><%= f.label :p2, "Son nom d'invocateur" %>
                <%= f.text_field :p2 %><br><br><%= f.label :c2, "Son champion" %>
                <%= f.text_field :c2 %><br></span><small class="mbr-price-term"></small>
                          </div>
                          <small class="mbr-plan-price-desc"></small>
                      </div>
                    </div>
                    <div class="mbr-plan-body card-block">
                      <div class="mbr-plan-list"></div>
                      <div class="mbr-plan-btn"><a href="https://mobirise.com" class="btn btn-white btn-white-outline">DEMO</a></div>
                    </div>
                </div>
            </div>
          </div>
    </div>
 <% end %>
</section>

<section class="engine"><a rel="external" href="https://mobirise.com">easy bootstrap web maker</a></section><footer class="mbr-small-footer mbr-section mbr-section-nopadding" id="footer1-d" style="background-color: rgb(50, 50, 50); padding-top: 1.75rem; padding-bottom: 1.75rem;">
    
    <div class="container">
        <p class="text-xs-center">League Rivals isn't endorsed by Riot Games and doesn't reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.<br><br>League Rivals | <a href="https://github.com/Zepri/LeagueRivals" target="_blank" class="text-success">Github</a></p>
    </div>
</footer>


  <script src="assets/web/assets/jquery/jquery.min.js"></script>
  <script src="assets/tether/tether.min.js"></script>
  <script src="assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets/smooth-scroll/SmoothScroll.js"></script>
  <script src="assets/theme/js/script.js"></script>
  
  
</body> -->
</html>

app/views/players/index.html.erb
<div class="mbr-section mbr-section-hero mbr-section-full" id="header1-1" data-bg-video="https://www.youtube.com/embed/Mgrr_SShwpg?rel=0&amp;amp;showinfo=0&amp;autoplay=1&amp;loop=1">

    <div class="mbr-overlay" style="opacity: 0.1; background-color: rgb(0, 0, 0);"></div>

    <div class="mbr-table-cell">

        <div class="container">
            <div class="row">
                <div class="mbr-section col-md-10 col-md-offset-1 text-xs-center">

                    <h1 class="mbr-section-title display-1">League Rivals<br><br></h1>
                    <p class="mbr-section-lead lead">Défiez vos amis !<br>Affrontez-vous lors d'un combat !</p>
                </div>
            </div>
        </div>
    </div>

    

</div>
<div class="mbr-section" id="pricing-table1-e" style="background-color: white; padding-top: 40px; padding-bottom: 120px;">
<p style="margin-left:auto;margin-right: auto;width:700px;"> Pour une liste des champions, veuillez vous rendre <a target="_blank" href="http://gameinfo.euw.leagueoflegends.com/en/game-info/champions/" >ici</a> <br>Vous n'avez pas de compte ? <br> Utilisez Zeprionrails comme nom d'invocateur et choisissez vos champions préférés !<br><br><span style="color:#b30000;"> -Veuillez écrire votre pseudo sans espace: Zepri on Rails => Zeprionrails <br> -Utilisez les noms de champions en anglais (voir le lien au dessus)</span></p>

  <%= form_for :player, url: players_path do |f| %>
    <div class="mbr-section mbr-section-nopadding mbr-price-table">
      <div class="row">
            <div class="col-xs-12 col-md-6 col-xl-4">
                <div class="mbr-plan card text-xs-center">
                    <div class="mbr-plan-header card-block">
                      <div class="card-text">
                          <div class="mbr-price">
                            <span class="mbr-price-desc"><%= f.label :p1, "Votre nom d'invocateur"  %>
                            <%= f.text_field :p1 %><br><br><%= f.label :c1, "Votre champion" %>
                            <%= f.text_field :c1 %><br></span><small class="mbr-price-term"></small>
                          </div>
                      </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 col-xl-4">
                <div class="mbr-plan card text-xs-center">
                    <div class="mbr-plan-body card-block"><%= f.submit "Combattre" %>
                    </div>
                </div>
            </div>
            
            <div class="col-xs-12 col-md-6 col-xl-4">
                <div class="mbr-plan card text-xs-center">
                    <div class="mbr-plan-header card-block">
                      <div class="card-text">
                          <div class="mbr-price">
                            <span class="mbr-price-desc"><%= f.label :p2, "Son nom d'invocateur" %>
                <%= f.text_field :p2 %><br><br><%= f.label :c2, "Son champion" %>
                <%= f.text_field :c2 %><br></span><small class="mbr-price-term"></small>
                          </div>
                      </div>
                    </div>
                </div>
            </div>
          </div>
    </div>
 <% end %>
</div>

<%= render 'footer' %>

app/views/players/show.html.erb
<div class="mbr-section mbr-section-hero mbr-section-full" id="header5-f" style="background-image: url('http://ddragon.leagueoflegends.com/cdn/img/champion/splash/<%= @player.c1 %>_0.jpg');background-size: cover; height: 717px;">

    

    <div class="mbr-table-cell">

        <div class="container">
            <div class="row">
                <div class="mbr-section col-md-10">

                    <h1 class="mbr-section-title display-1"><%= @player.p1.capitalize %></h1>
                    <p class="mbr-section-lead lead"></p>
                    
                </div>
            </div>
        </div>
    </div>

</div>

<div class="mbr-section mbr-section-hero mbr-section-full mbr-parallax-background mbr-section-with-arrow" id="header5-g" style="background-image: url('http://ddragon.leagueoflegends.com/cdn/img/champion/splash/<%= @player.c2 %>_0.jpg');background-size: cover;background-size: cover; height: 717px;background-attachment: fixed;">

    

    <div class="mbr-table-cell">

        <div class="container">
            <div class="row">
                <div class="mbr-section col-md-10 col-md-offset-2 text-xs-right">

                    <h1 class="mbr-section-title display-1"><%= @player.p2.capitalize %></h1>
                    
                    
                </div>
            </div>
        </div>
    </div>

</div>

<div class="mbr-section mbr-section-hero mbr-section-full mbr-section-with-arrow" id="header5-h">

    

  <div class="mbr-table-cell">

    <div class="container">

      <div class="row">

        <div class="mbr-section col-md-10 col-md-offset-1 text-xs-center" style="min-height:100%">
<!-- Si p1 a un meilleur winrate, alors .. -->
<%= if Player.determine_champion_probability(@player.p1, @player.c1)>Player.determine_champion_probability(@player.p2, @player.c2)
    #if win
    wonned

    else
    #if lost
    loosed
                                      end %>
        </div>
      </div>
    </div>
  </div>

</div>

<div class="mbr-section article" id="msg-box3-i" style="background-color: rgb(242, 242, 242); padding-top: 80px; padding-bottom: 80px;">

    
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-xs-center">
                
                
                <button><%= link_to "Nouveau combat ?", players_path %></button>
            </div>
        </div>
    </div>

</div>

<%= render 'footer' %>


  <script src="assets/javascripts/web/assets/jquery/jquery.min.js"></script>
  <script src="assets/javascripts/tether/tether.min.js"></script>
  <script src="assets/javascripts/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets/javascripts/smooth-scroll/SmoothScroll.js"></script>
  <script src="assets/javascripts/jarallax/jarallax.js"></script>
  <script src="assets/javascripts/css/theme/js/script.js"></script>